### ISSUE TITLE
[error] etcd makefile can't into the directory

### ISSUE THREAD

**Issue by JiChenSSG** [hertz-contrib/registry#114]
**Describe the bug**

Makefile under etcd directory have such code

```
prepare-cluster:
	cd example
	docker-compose up -d
```

it should be

```
prepare-cluster:
        cd example && docker-compose up -d
```

**To Reproduce**

```
cd etcd
make
```

**Comment by smx-Morgan** [comment]
我复现一下这个问题

**Comment by JiChenSSG** [comment]
> “cd example && docker-compose up -d” This command can indeed better bind these two operations, and this logic will be modified in the new registry repository.

That will be great.
