### ISSUE TITLE
请问 ETCD 的验证方式支持吗？

### ISSUE THREAD

**Issue by jetsung** [hertz-contrib/registry#31]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

当 ETCD 开启了用户名和密码验证时，如何使用？Kitex 的方案带验证的功能，`Hertz` 这边我查了下，没有找到相关的方案。

**Describe alternatives you've considered**

**Additional context**

**Comment by li-jin-gou** [comment]
It doesn't look supported, would you like to submit a PR?

**Comment by L2ncE** [comment]
Update to latest version, use `etcd.WithAuthOpt(username, password)`
