### ISSUE TITLE
nacos Resolve方法错误的过滤了结果

### ISSUE THREAD

**Issue by KafuuEriri** [hertz-contrib/registry#93]
**Describe the bug**

使用nacos作为注册中心，成功注册了服务端，客户端请求时报错service not found

**To Reproduce**
定义到问题出自https://github.com/hertz-contrib/registry/blob/133a1ea5b0d078bbd9b76997ffa3706edb1f2557/nacos/resolver.go#L108

<img width="909" alt="image" src="https://github.com/hertz-contrib/registry/assets/58974943/1a0029a6-88da-4246-83fd-9d3c17ab0db8">
<img width="368" alt="image" src="https://github.com/hertz-contrib/registry/assets/58974943/53e56934-8a23-431a-b462-1b895bdd9aac">
是否应该增加一个判断当metadata为空时不执行compareMaps
**Expected behavior**

**Screenshots**

**Hertz version:**

0.6.7

**Environment:**

1.21

**Additional context**

**Comment by li-jin-gou** [comment]
@KafuuEriri 可以提个 PR 修复一下它嘛

**Comment by li-jin-gou** [comment]
cc @Skyenought

**Comment by Skyenought** [comment]
server 测有设置 tag 吗?

**Comment by KafuuEriri** [comment]
> server 测有设置 tag 吗?

server是java服务带了preserved.register.source=SPRING_CLOUD,客户端使用了hz client

**Comment by Skyenought** [comment]
请问你 res[0] 的 metadata 里面真的是空的吗?

**Comment by KafuuEriri** [comment]
> 请问你 res[0] 的 metadata 里面真的是空的吗?

```
var metadata map[string]string
	serviceName := desc

	// Get serviceName and metadata from desc
	if strings.Contains(desc, "?") {
		queries, _ := url.Parse(desc)
		tags, _ := url.ParseQuery(queries.Query().Encode())

		result := make(map[string]string)
		for key, value := range tags {
			result[key] = value[0]
		}
		metadata = result
		serviceName = strings.Split(desc, "?")[0]
	}
```
空的metadata来自这段代码，res中的metadata为 preserved.register.source -> SPRING_CLOUD
