### ISSUE TITLE
Feature request: Support nacos v2 sdk 

### ISSUE THREAD

**Issue by li-jin-gou** [hertz-contrib/registry#96]
**Is your feature request related to a problem? Please describe.**

- The nacos v2 sdk is not currently supported.

**Describe the solution you'd like**

- Support nacos v2 sdk

**Describe alternatives you've considered**

- None

**Additional context**

- Add a new naocs-v2 directory, managed using submodule
- sdk repo: https://github.com/nacos-group/nacos-sdk-go

**Comment by AllianceTing** [comment]
can I have a try?
